### PR TITLE
Logging Structure Harmonized

### PR DESCRIPTION
**Pull request by Ayybeeshafi**
Logging done with AKKA framework and regular logging now have the same structure.
First comes the level, then date and then the logger.

### CODE REVIEW

**Comment by bhermann** [comment]
I think you are in the wrong repository for this fix. This was an issue of the delphi-crawler repo.

**Comment by bhermann** [comment]
Oh ... I see you are doing for all repos! Even better! Thanks!

**Comment by Ayybeeshafi** [comment]
The issue said, you have to configure the configuration files of AKKA and regular logging but the application.conf and logback.xml are not present in the crawler repository. I cant seem to find out in the crawler repo where logging is configured.

**Comment by bhermann** [comment]
Yeah... that was kind of the point of issue delphi-hub/delphi-crawler#8 ... :-)
Technically, it's a standard actor model project and you can put the same configs there as in the other projects.

**Comment by bhermann** [comment]
Nevertheless, very good that you harmonize the configs over all project also.

**Comment by Ayybeeshafi** [comment]
So I created the same **conf** folder with **application.xml, logback.xml** and **routes** files in it for crawler repo.

After solving the dependency issues. The console is still showing default scala logging. I have looked into all possible solutions but nothing on the web seem to workout. 

One solution said that you have to disable the scala default logging that too I cant seem to figure out.
If you can point us to the direction where we should look to get this issue solved.

There is another concern that maybe we are unable to run the part of the program that trigger this logging system. Have a look at the screenshot of console.

image

**Comment by bhermann** [comment]
Let's check this tomorrow together. 👍

**Pull request merged**
